config/routes.rb
Furiana::Application.routes.draw do
  resources :commissions

  get "pages/home"

  get "pages/about"

  get "pages/tos"

  get "pages/prices"

  get "pages/subjects"

  get "pages/shipping"

  get "pages/queue"
  
  match '/about', :to => 'pages#about'
  match '/tos', :to => 'pages#tos'
  match '/prices', :to => 'pages#prices'
  match '/subjects', :to => 'pages#subjects'
  match '/shipping', :to => 'pages#shipping'
  match '/queue', :to => 'commissions#index'
  

root :to => 'pages#home'

end

app/models/commission.rb
# Attributes that I added:
# commissioner:string
# commission:string
# info:boolean
# first_payment:boolean
# sketch_completed:boolean
# final_payment:boolean
# high_res_sent:boolean
# shipped:boolean
# est_completion:string

class Commission < ActiveRecord::Base
	attr_accessible :commissioner, :commission, :info, :first_payment, :sketch_completed, :final_payment, :high_res_sent, :shipped, :est_completion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/commissions_controller.rb
class CommissionsController < ApplicationController
  # GET /commissions
  # GET /commissions.json
  def index
    @commissions = Commission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commissions }
    end
  end

  # GET /commissions/1
  # GET /commissions/1.json
  def show
    @commission = Commission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @commission }
    end
  end

  # GET /commissions/new
  # GET /commissions/new.json
  def new
    @commission = Commission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @commission }
    end
  end

  # GET /commissions/1/edit
  def edit
    @commission = Commission.find(params[:id])
  end

  # POST /commissions
  # POST /commissions.json
  def create
    @commission = Commission.new(params[:commission])

    respond_to do |format|
      if @commission.save
        format.html { redirect_to @commission, notice: 'Commission was successfully created.' }
        format.json { render json: @commission, status: :created, location: @commission }
      else
        format.html { render action: "new" }
        format.json { render json: @commission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commissions/1
  # PUT /commissions/1.json
  def update
    @commission = Commission.find(params[:id])

    respond_to do |format|
      if @commission.update_attributes(params[:commission])
        format.html { redirect_to @commission, notice: 'Commission was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @commission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commissions/1
  # DELETE /commissions/1.json
  def destroy
    @commission = Commission.find(params[:id])
    @commission.destroy

    respond_to do |format|
      format.html { redirect_to commissions_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = nil
  end

  def about
	@title = "About"
  end

  def tos
	@title = "Terms of Service"
  end

  def prices
	@title = "Price Guide"
  end

  def subjects
	@title = "Subject Guide"
  end

  def shipping
	@title = "Shipping Rates"
  end

  def queue
	@title = "Queue"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def title
		base_title = "Furiana's Artwork"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
		
end

app/helpers/commissions_helper.rb
module CommissionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/commissions/_form.html.erb
<%= form_for(@commission) do |f| %>
  <% if @commission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commission.errors.count, "error") %> prohibited this commission from being saved:</h2>

      <ul>
      <% @commission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commissioner %><br />
    <%= f.text_field :commissioner %>
  </div>
  <div class="field">
    <%= f.label :commission %><br />
    <%= f.text_field :commission %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.check_box :info %>
  </div>
  <div class="field">
    <%= f.label :first_payment %><br />
    <%= f.check_box :first_payment %>
  </div>
  <div class="field">
    <%= f.label :sketch_completed %><br />
    <%= f.check_box :sketch_completed %>
  </div>
  <div class="field">
    <%= f.label :final_payment %><br />
    <%= f.check_box :final_payment %>
  </div>
  <div class="field">
    <%= f.label :high_res_sent %><br />
    <%= f.check_box :high_res_sent %>
  </div>
  <div class="field">
    <%= f.label :shipped %><br />
    <%= f.check_box :shipped %>
  </div>
  <div class="field">
    <%= f.label :est_completion %><br />
    <%= f.text_field :est_completion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commissions/edit.html.erb
<h1>Editing commission</h1>

<%= render 'form' %>

<%= link_to 'Show', @commission %> |
<%= link_to 'Back', commissions_path %>

app/views/commissions/index.html.erb
<h1>Queue</h1>

<% @commissions.each do |commission| %>
<div class="panel">
<ul>
<li><strong>Commissioner:</strong> <%= commission.commissioner %></li>
<li><strong>Project:</strong> <%= commission.commission %></li>
<li><strong>Info received:</strong> <%= commission.info %></li>
<li><strong>First payment received:</strong> <%= commission.first_payment %></li>
<li><strong>Sketch completed:</strong> <%= commission.sketch_completed %></li>
<li><strong>Final payment received:</strong> <%= commission.final_payment %></li>
<li><strong>High resolution file sent:</strong> <%= commission.high_res_sent %></li>
<li><strong>Shipped:</strong> <%= commission.shipped %></li>
<li><strong>Estimated completion date:</strong> <%= commission.est_completion %></li>
<li><%= link_to 'Show', commission %> <%= link_to 'Edit', edit_commission_path(commission) %> <%= link_to 'Destroy', commission, confirm: 'Are you sure?', method: :delete %></li>
</ul>
</div>
<% end %>

<%= link_to 'Add Commission', new_commission_path %>

app/views/commissions/new.html.erb
<h1>New commission</h1>

<%= render 'form' %>

<%= link_to 'Back', commissions_path %>

app/views/commissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commissioner:</b>
  <%= @commission.commissioner %>
</p>

<p>
  <b>Commission:</b>
  <%= @commission.commission %>
</p>

<p>
  <b>Info:</b>
  <%= @commission.info %>
</p>

<p>
  <b>First payment:</b>
  <%= @commission.first_payment %>
</p>

<p>
  <b>Sketch completed:</b>
  <%= @commission.sketch_completed %>
</p>

<p>
  <b>Final payment:</b>
  <%= @commission.final_payment %>
</p>

<p>
  <b>High res sent:</b>
  <%= @commission.high_res_sent %>
</p>

<p>
  <b>Shipped:</b>
  <%= @commission.shipped %>
</p>

<p>
  <b>Est completion:</b>
  <%= @commission.est_completion %>
</p>


<%= link_to 'Edit', edit_commission_path(@commission) %> |
<%= link_to 'Back', commissions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
	<div class="twelve columns">
		<div id="featured"> 
			<img src="/assets/orbit/overflow.jpg" alt="Overflow" data-caption="#htmlCaption"/>
			<img src="/assets/orbit/captions.jpg" alt="HTML captions" data-caption="#htmlCaption2" />
			<img src="/assets/orbit/features.jpg" alt="and more features" />
		</div>
		<span class="orbit-caption" id="htmlCaption"><strong>I'm A Badass Caption:</strong> I can haz <a href="#">links</a>, <em>style</em> or anything that is valid markup :)</span>
		<span class="orbit-caption" id="htmlCaption2"><strong>I'm Also A Badass Caption:</strong> Isn't this cool?!</span>
	</div>
	</div>
	
	<div class="row">
	<div class="twelve columns">
		<ul class="nav-bar">
			<li><%= link_to "Terms of Service", tos_path %></li>
			<li><%= link_to "Price guide", prices_path %></li>
			<li><%= link_to "Subject guide", subjects_path %></li>
			<li><%= link_to "Shipping Rates", shipping_path %></li>
			<li><%= link_to "Queue", queue_path %></li>
			<li><%= link_to "Feedback", "#" %></li>
		</ul>
	</div>
	</div>
		
	<div class="row">
	<div class="twelve columns">
		<%= yield %>
	</div>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Commissions List", commissions_path %>

app/views/pages/prices.html.erb
<h1>Pages#prices</h1>
<p>Find me in app/views/pages/prices.html.erb</p>

app/views/pages/queue.html.erb
<h1>Pages#queue</h1>
<p>Find me in app/views/pages/queue.html.erb</p>

app/views/pages/shipping.html.erb
<h1>Pages#shipping</h1>
<p>Find me in app/views/pages/shipping.html.erb</p>

app/views/pages/subjects.html.erb
<h1>Pages#subjects</h1>
<p>Find me in app/views/pages/subjects.html.erb</p>

app/views/pages/tos.html.erb
<h1>Terms of Service</h1><br>

<h3>General Information</h3><br>
<p>These terms of service apply to non-commercial commissions only.  They are subject to revision at any time.
<p><strong>By sending payment, you [agree] that you have read and understood these Terms of Service, and you [agree to be bound by them].</strong></p><br>

<div class="panel">
<h3>Contact Information</h3><br>
<p>I only discuss commissions via email.  However, if you lose contact with me, I'm also active on Nabyn and DeviantArt.</p>
<ol><ul>
<li>Email: furiana (at) live (dot) com
<li>Nabyn: http://furiana.nabyn.com
<li>DeviantArt: http://furiana.deviantart.com
</ul></ol>
</div>

<div class="panel">
<h3>How to Order</h3><br>
<p>Send your commission request to furiana at live dot com.  </p>
<ol><ul>
<li> You must include all relevant information including references and deadlines, as these can affect the final price.  If you would like the final piece to be shipped, please include the shipping address as well.
If the commission will involve characters that belong to other people, I will also need written permission from each character's owner before I begin.  Without it, I will not include them in the piece.
<li> I will send you a final quote.  This stays good for 3 weeks.  
<li> If you agree to the amount, I will send you a PayPal invoice for the first payment.  This must be paid within 30 days or the commission is considered cancelled.
</ul></ol>

<h4>Sketch phase</h4><br>
<p>After I receive the first payment, I will begin the sketch.</p>
<ol><ul>
<li>When it is complete, I will send you a watermarked, low resolution file (800 pixels on the longest side) of the rough sketch.  This is the best time to ask for revisions. 
<li>You will receive another WIP after each round of revisions until you approve the sketch.  Please note that free revisions are limited, and additional revisions cost more: see Revisions for more information.
</ul></ol>

<h4>Coloring phase</h4><br>
<p>If applicable, coloring begins once you approve the sketch.</p>
<ol><ul>
<li> I will send a WIP when the background is completed.  I can also send WIPs upon request.  Minor edits are allowed during this stage, but depending on the medium, the piece, and the degree of completion, they may not be possible.
</ul></ol>

<h4>Final payment and shipping</h4><br>
<h9> When the image is finished, I will send a low-resolution, heavily watermarked version as proof of completion.  I will also send an invoice for the final payment.</h9><br><br>
<ol><ul><li>Refunds are no longer possible at this stage.
<li>Once the final payment has been made, I will send you the high-resolution version of the image (2000 pixels on the longest side).  I can also ship the original to you, as outlined below.</ul></ol>
</div>

<div class="panel">
<h3>Payment</h3><br>
<h9>I send PayPal invoices, which let you use PayPal, credit card, or bank transfer.  I accept USD and CAD.</h9><br><br>
<ol><ul><li>For orders under $100, I require half up front and half upon proof of completion.
<li>For orders above $100, payment plans are available.  I always require 30% before beginning the sketch.  I usually require another 30% before I begin coloring, and the rest (40%) upon proof of completion.  Please contact me for more information1
</ul></ol>
</div>

<div class="panel">
<h3>Deadlines and Turnaround</h3><br>
<p>You can see my queue <%= link_to "here", queue_path %>. Order is based on when payments are received.
<p>Single-character sketches take two to four business days to complete.  Full-color illustrations average two to three months, depending on their complexity.  The rest are somewhere in between.
<ol><ul><li>If you have a deadline, I will do my best to meet it.  However, unless I'm told about the deadline at the beginning (before the first payment is made), I cannot guarantee that the piece will be done in time.  
<li>Rush orders are subject to non-refundable flat fee of 25%.  I also offer express shipping at the customer's expense.
</ul></ol>
</div>

<div class="panel">
<h3>Refunds</h3><br>
<p>The artist and the customer have the right to cancel the commission at any time.
<ol><ul><li>Under most circumstances, the customer can choose between a partial refund plus any work completed, or a full refund.  If the customer chooses a partial refund, they can ask for the original to be shipped at their expense.  If the customer chooses a full refund, they forfeit their claim to the image, and the artist can recycle it as she sees fit.
<li>If the artist loses contact with the customer for 6 weeks without notice, the artist will cancel the commission and offer a refund.  If the customer does not respond for another 3 weeks, the artist has the right to keep the balance and recycle the image as she sees fit.
</ul></ol></div>

<div class="panel">
<h3>Revisions</h3><br>
<p>For pieces under $100, I allow one major edit and two minor edits.
<p>For pieces over $100, I allow three major edits and four minor edits.
<p>Additional minor edits cost $5 each.  Additional major edits cost $10 and up.  Completely redrawing the image costs the same as a sketch.
<ol><ul><li>Minor edits include: redrawing a hand; adding a simple bracelet; adding a boulder to the background; adjusting the color of a small, shaded area (ex, from blue to greenish-blue).
<li>Major edits include: redrawing an arm; adding a complex headdress; adding cliffs to the background; completely changing the color of a large, shaded area (ex, from blue to red).
</ul></ol>
<p>The artist's mistakes do not count towards the total and will be fixed for free.  This does not include errors caused by incomplete references or forgetfulness/poor communication on the customer's part.

</div>

<div class="panel">
<h3>Usage Rights</h3><br>
<p>The customer is paying for the Artist's service, not for the rights to the image.  The artist retains authorship of the image at all times.  The Artist also retains all rights unless she explicitly states otherwise.
<p>All of the Artist's artwork is distributed under a Creative Commons Attribution, Non-Commercial, Share-Alike 3.0 License.  (For the details, please see <%= link_to "this page", "http://creativecommons.org/licenses/by-nc-sa/3.0/" %>.)
<ol><ul><li>If the customer wants to use the piece for profit, additional rights can be licensed for a fee.  Please contact me with how the piece would be used (on a CD cover, as online advertising, etc.) and how long it would be for (one time use, six months, etc.) in order to receive a quote.</ul></ol>